---
title: "Twitter Coffee"
author: "Susie Tan"
date: "07/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rtweet)
```

## Data import

Step 1. collect tweets about coffee

# this way takes time, update everytime, search through n=1800 each time
#if you have retryonratelimit, if it is too much, it is going to take a break - then restarts again
# leverage load on server - so they pace you out - "can you wait?"
#coffee_tweets%>%write_csv("coffee_7_10_21.csv") - merge, download and save twitter -just run this line

```{r eval=FALSE}
coff_tweets<-search_tweets(
  q="coffee",
  n=1800,
  include_rts = FALSE,
  lang="en",
  retryonratelimit = TRUE
)

coff_tweets%>%
  select(-hashtags,-symbols,-urls_url)%>%
  write_csv("coffee_7_10_21.csv")
```

```{r}

# look at first 6 observations
coff_tweets%>%
  head()

# look at structure
coff_tweets%>%
  str()

coffee_short <- coff_tweets%>%
  select(user_id, screen_name, created_at, text, favourites_count,retweet_count)

coffee_short%>%write_csv("coffee_short_7_10_21.csv")
```

